### PR TITLE
solution to hw4 : part 1

### PR DESCRIPTION
**Pull request by EllieSky**

### CODE REVIEW

**Review by okov1 — APPROVED** [review]
Everything fine

**Comment by milters** [comment]
done

**Review by vadimgumarov — COMMENTED** [review]
Approved

**Review by milters — APPROVED** [review]

**Review by constantinefilonov — APPROVED** [review]

**Comment by Linokkonek** [comment]
Approved

**Review by Linokkonek — APPROVED** [review]

**Pull request merged**
